HMS/patient/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField, DateTimeField, HiddenField, IntegerField
from wtforms.validators import DataRequired, regexp, ValidationError, optional
from HMS.cities import getstates, getcities
from HMS.models import Patient
from datetime import datetime


class NonValidatingSelectField(SelectField):
    def pre_validate(self, form):
        pass


class PatientRegistrationForm(FlaskForm):
    ssnid = StringField('Patient SSN Id', validators=[DataRequired()], render_kw={'readonly': True})
    patientName = StringField('Patient Name', validators=[DataRequired()])
    age = IntegerField('Patient Age', validators=[DataRequired()])
    dateOfAdmission = DateTimeField('Date of Admission', validators=[DataRequired()], default=datetime.now().replace(microsecond=0), render_kw={'readonly': True})
    roomType = SelectField('Type of Bed', validators=[DataRequired()], choices=[('', 'Select Room'),('General', 'General ward'),('Sharing', 'Semi sharing'), ('Single', 'Single room')])
    patientaddress = TextAreaField('Address', validators=[DataRequired()])
    state = SelectField('State', validators=[DataRequired()], choices=[(state,state) for state in getstates()])
    city = NonValidatingSelectField('City', validators=[DataRequired()], choices=[])
    submit = SubmitField('Submit')

    def validate_dateOfAdmission(self, dateOfAdmission):
        if self.dateOfAdmission.data > datetime.now():
            raise ValidationError('Please provide correct date of admission')

    def validate_age(self, age):
        if int(self.age.data) > 150:
            raise ValidationError('Age must be below 150')


class PatientUpdateForm(FlaskForm):
    patientId = StringField('Patient Id', validators=[DataRequired()], render_kw={'readonly': True})
    name = StringField('Patient New Name', validators=[optional()])
    age = StringField('Patient New Age', validators=[optional()])
    address = TextAreaField('New Address', validators=[optional()])
    state = SelectField('State', validators=[optional()], choices=[(state,state) for state in getstates()])
    city = NonValidatingSelectField('City', validators=[optional()], choices=[])
    submit = SubmitField('Update')


class PatientDelete(FlaskForm):
    pid = HiddenField(validators=[DataRequired()])
    submit = SubmitField('Confirm Delete')


class PatientDischarge(FlaskForm):
    pid = HiddenField(validators=[DataRequired()])
    nexturl = HiddenField(validators=[DataRequired()])
    dateOfDischarge = HiddenField(validators=[DataRequired()], default=datetime.now().replace(microsecond=0))
    formData = HiddenField(validators=[DataRequired()])
    submit = SubmitField('Confirm & Proceed')

HMS/patient/__init__.py
from flask import Blueprint

patient = Blueprint('patient', __name__)

from HMS.patient import routes

HMS/patient/routes.py
from HMS import db, bcrypt
from HMS.patient import patient
from flask import render_template, redirect, request, url_for, flash, jsonify, abort
from flask_login import login_required
from HMS.patient.forms import PatientRegistrationForm, PatientUpdateForm, PatientDischarge, PatientDelete
from HMS.cities import getstates, getcities
from HMS.models import Patient, Medicines, Diagnostics, MedicineMaster, DiagnosticMaster
from random import randint
import json
from datetime import datetime


def random_num():
    start = 10**8
    end = (10**9)-1
    return randint(start, end)

def checkPid(pid, status=None):
    if status is None:
        patient = Patient.query.filter_by(patientId=pid).first_or_404()
    else:
        patient = Patient.query.filter_by(patientId=pid, status=status).first_or_404()
    if patient:
        return patient


# City Route
@patient.route('/city/<selectState>')
@login_required
def city(selectState):
    states = getstates()
    for i, state in enumerate(states):
        if state == selectState:
            n = i
            break
    cities = getcities()[int(n)]
    cityArray = []
    for city in cities:
        cityObj = {}
        cityObj['id'] = city[0]
        cityObj['name'] = city[1]
        cityArray.append(cityObj)
    return jsonify({'cities': cityArray})


# Patient Route
@patient.route('/register', methods=['GET', 'POST'])
@login_required
def register(): 
    title = 'Namaste Hospitals | Patient Registration'
    form = PatientRegistrationForm()
    form.ssnid.data = int(Patient.query.count()) + 100000001
    if request.method == 'POST' and form.validate_on_submit():
        doa = request.form.get('dateOfAdmission')
        id=0
        while True:
            id = random_num()
            if not Patient.query.filter_by(patientId=id).first():
                break
        newPatient = Patient(
            ssnid=form.ssnid.data,
            patientId=id,
            name=request.form.get('patientName'),
            age=request.form.get('age'),
            dateOfJoining = datetime.strptime(doa, '%Y-%m-%d %H:%M:%S'),
            roomType=request.form.get('roomType'),
            address=request.form.get('patientaddress'),
            city=request.form.get('city'),
            state=request.form.get('state')
            )
        db.session.add(newPatient)
        db.session.commit()
        flash(f'Patient Registration initiated successfully! Patient Id : {id}', 'success')
        return redirect(url_for('patient.register'))
    return render_template('patient/register.html', title=title, form=form, cdate=datetime.now().strftime("%Y-%m-%d %H:%M:%S"))


# Update Patient
@patient.route('/update', methods=['GET','POST'])
@login_required
def update():
    pid = request.args.get('pid')
    if pid is None:
        return redirect(url_for('main.search', next='patient.update'))
    p = checkPid(pid, True)
    title = 'Namaste Hospitals | Patient Update'
    form = PatientUpdateForm()
    form.patientId.data = p.patientId
    form.name.data = p.name
    form.age.data = p.age
    form.address.data = p.address
    form.state.data = p.state
    form.city.data = p.city
    if request.method == 'POST' and form.validate_on_submit():
        p.name = request.form.get('name')
        p.age = request.form.get('age')
        p.address = request.form.get('address')
        p.state = request.form.get('state')
        if request.form.get('city'):
            p.city = request.form.get('city')
        db.session.commit()
        flash(f'Patient Updation initiated successfully! Patient Id : {pid}','success')
        return redirect(url_for('patient.details', pid=pid))
    return render_template('patient/update.html', form=form, title=title, patient=p)
        

    
#delete Patient
@patient.route('/delete', methods=['GET','POST'])
@login_required
def delete():
    pid = request.args.get('pid')
    if pid is None:
        return redirect(url_for('main.search', next='patient.delete'))
    p = checkPid(pid)
    title = 'Namaste Hospitals | Patient Delete'
    form = PatientDelete()
    form.pid.data = pid
    if request.method == 'POST' and form.validate():
        id = request.form.get('pid')
        if p.status:
            flash(f'Awaiting Payment for Patient. Redirecting to Billing page...', 'danger')
            return redirect(url_for('patient.billing', next='patient.delete', pid=id))
        else:
            Medicines.query.filter_by(patientId=id).delete()
            Diagnostics.query.filter_by(patientId=id).delete()
            Patient.query.filter_by(patientId=id).delete()
        db.session.commit()
        flash(f'Patient Deletion initiated successfully! Patient Id: {id}','success')
        return redirect(url_for('main.home'))
    return render_template('patient/delete.html', p=p, form=form)


# Patient Details Route
@patient.route('/details-single', methods=['GET', 'POST'])
@login_required
def details():
    pid = request.args.get('pid')
    if pid is None:
        return redirect(url_for('main.search', next='patient.details'))
    title = 'Namaste Hospitals | Patient | Details'
    p = checkPid(pid)
    if p.status is False:
        flash(f'Patient with id : {pid} is discharged. To check details go to All Records.', 'danger')
        return redirect(url_for('patient.details'))
    return render_template('patient/patientDetails.html', p=p, pid=pid)


# Patients Status Route
@patient.route('/details-all', methods=['GET', 'POST'])
@login_required
def status():
    title = 'Namaste Hospitals | Patient | Status'
    patient = Patient.query.all()
    return render_template('patient/allPatientsDetails.html', patient=patient)


# Patient Billing Route
@patient.route('/billing')
@login_required
def billing():
    pid = request.args.get('pid')
    nexturl = request.args.get('next')
    if pid is None:
        return redirect(url_for('main.search', next='patient.billing'))
    patient = checkPid(pid)
    title = 'Namaste Hospitals | Patient Billing'
    form = PatientDischarge()
    form.pid.data = pid
    form.nexturl.data = nexturl
    btn = True
    if patient.dateOfDischarge:
        dod = patient.dateOfDischarge
        flash(f'Patient with id : {pid} is already discharge', 'info')
        btn = False
    else:
        dod = datetime.now().replace(microsecond=0)
    personal = [patient.name, patient.age, f'{patient.address}, {patient.city}, {patient.state}']
    dates = [patient.dateOfJoining, dod ]
    if patient.roomType == 'General' :
        roomtype = 'General ward'
        roomrent = 2000
    elif patient.roomType == 'Sharing':
        roomtype = 'Semi sharing'
        roomrent = 4000
    else:
        roomtype = 'Single room'
        roomrent = 8000
    datediff = dates[1]-dates[0]
    dateHr = datediff.total_seconds() // 3600
    daycount = f'{int(dateHr // 24)} Days {int(dateHr % 24)} hours'
    money = round(((roomrent*(dateHr // 24))+((roomrent / 24)*(dateHr % 24))), 2)
    rents = [roomtype, daycount, roomrent, money]
    mamount = tamount = 0
    medicines = []
    mids = Medicines.query.filter_by(patientId=pid).all()
    for i in range(len(mids)):
        med = {}
        medicine = MedicineMaster.query.filter_by(medicineId=mids[i].medicineId).first()
        med['count'] = i+1;
        med['name'] = medicine.medicineName
        med['qty'] = mids[i].quantity
        med['rate'] = medicine.rate
        med['amount'] = mids[i].quantity*medicine.rate
        medicines.append(med)
        mamount += mids[i].quantity*medicine.rate
    tests = []
    dids = Diagnostics.query.filter_by(patientId=pid).all()
    for i in range(len(dids)):
        tt = {}
        test = DiagnosticMaster.query.filter_by(testId=dids[i].testId).first()
        tt['count'] = i+1;
        tt['name'] = test.testName
        tt['rate'] = test.rate
        tests.append(tt)
        tamount += test.rate
    totalamount = [mamount, tamount]
    return render_template('patient/billing.html', title=title, medicines=medicines, tests=tests, personal=personal, dates=dates, rents=rents, totalamount=totalamount, pid=pid, btn=btn, form=form)


# Generate PDF Route
@patient.route('/genratePDF', methods=['POST'])
@login_required
def genPDF():
    pid = request.form.get('pid')
    nexturl = request.form.get('nexturl')
    if pid is None:
        abort(404)
    checkPid(pid, True)
    data = {
        "pid" : pid,
        "next" : nexturl,
        "dod" : request.form.get('dateOfDischarge'),
        "key" : bcrypt.generate_password_hash(pid).decode('utf-8'),
        "formData" : request.form.get('formData')
    }
    return render_template('patient/genratePdf.html', title=f'Billing Details | {pid}', data=data)


# Patient Discharge Route
@patient.route('/patientDischarge')
@login_required
def discharge():
    pid = request.args.get('pid')
    nexturl = request.args.get('next')
    dod = request.args.get('dod')
    key = request.args.get('key')
    if pid and bcrypt.check_password_hash(key, pid):
        p = checkPid(pid, True)
        print(p)
        p.dateOfDischarge = datetime.strptime(dod, '%Y-%m-%d %H:%M:%S')
        p.status = False
        db.session.commit()
        return redirect(url_for(nexturl or 'patient.billing', pid=pid))
    else:
        abort(404)

HMS/templates/patient/allPatientsDetails.html
{% extends 'layout.html' %}  
{% block cssContent %}
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/css/dataTables.bootstrap4.min.css') }}">
{% endblock cssContent %}
{% block mainContent %}
<div class="card col-12 my-3">
    <div class="card-header text-center bg-dark">
        <div class="card-title">
            <h2 class="font-monospace font-weight-bold text-info">All Patient's Details</h2>
        </div>
    </div>
    <div class="card-body alert-info">
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped" id="statustable">
                <thead class="bg-danger text-white">
                    <tr>
                        <th scope="col">SSN Id</th>
                        <th scope="col">Patient Id</th>
                        <th scope="col">Name</th> 
                        <th scope="col">Age</th>
                        <th scope="col">Address</th>
                        <th scope="col">Date of Joining</th>
                        <th scope="col">Type Of Room</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in patient %}   
                    <tr>
                        <td scope="row">{{ p.ssnid }}</td>
                        <td>{{ p.patientId }}</td>
                        <td>{{ p.name }}</td>
                        <td>{{ p.age }}</td>
                        <td>{{ p.address+', '+p.city+', '+p.state }}</td>
                        <td>{{ p.dateOfJoining }}</td>
                        <td>{{ p.roomType }}</td>
                        <td>{% if p.status %}<span class="badge bg-primary">Available</span>{% else %}<span class="badge bg-secondary">Discharge</span>{% endif %}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock mainContent %}
{% block jsContent %}
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $("#statustable").DataTable({
            "info": true,
            "order": [0 ,'desc']
        });
    </script>
{% endblock jsContent %}

HMS/templates/patient/billing.html
{% extends 'layout.html' %}
{% block mainContent %}
    <div class="container mb-5">
        <div id="printScreen">
            <div class="card col-12 my-3">
                <div class="card-header bg-dark">
                    <div class="card-title text-center font-weight-bold font-monospace pt-2">
                        <h2 class="text-info">Patient Billing / Discharge</h2>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive mb-3">
                        <h3 class="text-center font-monospace font-weight-bold text-danger text-decoration-underline">Patient Details</h3>
                        <table class="table table-hover table-bordered text-center">
                            <thead class="alert-info">
                                <th>Patient Name</th>
                                <th>Age</th>
                                <th>Address</th>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>{{ personal[0] }}</td>
                                    <td>{{ personal[1] }}</td>
                                    <td>{{ personal[2] }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="table-responsive mb-3">
                        <table class="table table-hover table-bordered text-center">
                            <thead class="alert-info">
                                <th>Date of Admission</th>
                                <th>Date of Discharge</th>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>{{ dates[0] }}</td>
                                    <td>{{ dates[1] }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="table-responsive mb-3">
                        <h3 class="text-center font-monospace font-weight-bold text-danger text-decoration-underline">Room Rent Details</h3>
                        <table class="table table-hover table-bordered text-center">
                            <thead class="alert-info">
                                <th>Hospital Room type</th>
                                <th>Number of Days in Hospital</th>
                                <th>Room Rent <small>( per day )</small></th>
                                <th class="text-danger">Total Room Rent</th>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>{{ rents[0] }}</td>
                                    <td>{{ rents[1] }}</td>
                                    <td>{{ rents[2] }}</td>
                                    <td class="font-weight-bold">{{ rents[3] }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="table-responsive mb-3">
                        <h3 class="text-center font-monospace font-weight-bold text-danger text-decoration-underline">Medicines Bill Details</h3>
                        <table class="table table-hover table-bordered text-center">
                            <thead class="alert-info">
                                <th>Sr. No</th>
                                <th>Medicine Name</th>
                                <th>Quantity</th>
                                <th>Rate <small>( per peice )</small></th>
                                <th>Amount</th>
                            </thead>
                            <tbody>
                                {% for medicine in medicines %} 
                                <tr>
                                    <td>{{ medicine.count }}</td>
                                    <td>{{ medicine.name }}</td>
                                    <td>{{ medicine.qty }}</td>
                                    <td>{{ medicine.rate }}</td>
                                    <td>{{ medicine.amount }}</td>
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td class="text-danger font-weight-bold">Total Amount</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td class="font-weight-bold">{{ totalamount[0] }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="table-responsive mb-3">
                        <h3 class="text-center font-monospace font-weight-bold text-danger text-decoration-underline">Diagnostics Bill Details</h3>
                        <table class="table table-hover table-bordered text-center">
                            <thead class="alert-info">
                                <th>Sr. No</th>
                                <th>Test Name</th>
                                <th>Amount</th>
                            </thead>
                            <tbody>
                                {% for test in tests %} 
                                <tr>
                                    <td>{{ test.count }}</td>
                                    <td>{{ test.name }}</td>
                                    <td>{{ test.rate }}</td>
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td class="text-danger font-weight-bold">Total Amount</td>
                                    <td></td>
                                    <td class="font-weight-bold">{{ totalamount[1] }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="card alert-info font-weight-bold py-2 my-3 font-monospace">
                        <div class="d-flex justify-content-around">
                            <h3 class="text-danger">Grand Total</h3>
                            <h3 class="text-danger text-decoration-underline">{{ rents[3]+totalamount[0]+totalamount[1] }}</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if btn %} 
        <div class="d-flex justify-content-center my-5">
            <button class="btn btn-danger rounded-0 text-white font-monospace font-weight-bold px-5" type="button" data-toggle="modal" data-target="#modalConfirm" onclick="addDataToForm();">Discharge Patient &amp; Generate Billing Invoice</button>
        </div>
        {% endif %}
    </div>
    <div class="modal fade" id="modalConfirm" tabindex="-1" aria-labelledby="modelConfirmLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content alert-warning">
                <div class="modal-header bg-danger">
                    <h5 class="modal-title text-dark font-monospace text-uppercase" id="modelConfirmLabel">Confirmation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p class="text-primary">Are your Confirm,</p>
                    <p class="text-dark">You want to discharge this patient <small class="text-danger">( id : {{ pid }} )</small> and generate billing invoice.</p>
                    <p class="text-info">If yes... Click on Confirm &amp; Proceed</p>
                    <p class="text-muted">else... Click on Close to cancel</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary mr-auto px-5" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('patient.genPDF') }}" method="POST">
                        {{ form.hidden_tag() }}
                        {{ form.submit(class="btn btn-success mr-auto px-5")}}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock mainContent %}
{% block jsContent %}
    <script>
        function addDataToForm() {
            document.getElementById('formData').value = document.getElementById('printScreen').innerHTML
        }
    </script>
{% endblock jsContent %}

HMS/templates/patient/delete.html
{% extends 'layout.html' %}
{% block mainContent %}
<div class="d-flex justify-content-center">
    <div class="card col-lg-4 col-md-8 col-12 mb-5 mt-3">
        <div class="card-header text-center bg-dark">
            <div class="card-title">
                <h2 class="font-monospace font-weight-bold text-info">Patient Details</h2>
            </div>
        </div>
        <div class="card-body alert-info">
            <div class="row">
                <p class="col-6 text-left font-weight-bold">SSN Id</p>
                <p class="col-6 text-right">{{ p.ssnid }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Patient Id</p>
                <p class="col-6 text-right">{{ p.patientId }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Patient Name</p>
                <p class="col-6 text-right">{{ p.name }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Patient Age</p>
                <p class="col-6 text-right">{{ p.age }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Date of Admission</p>
                <p class="col-6 text-right">{{ p.dateOfJoining }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Type of Bed</p>
                <p class="col-6 text-right">{{ p.roomType }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Address</p>
                <p class="col-6 text-right">{{ p.address }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">State</p>
                <p class="col-6 text-right">{{ p.state }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">City</p>
                <p class="col-6 text-right">{{ p.city }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Status</p>
                <p class="col-6 text-right">{% if p.status %}<span class="badge bg-primary">Available</span>{% else %}<span class="badge bg-secondary">Discharge</span>{% endif %}</p>
            </div>
            <div class="d-flex justify-content-center mt-5">
                <form action="" method="POST">
                    {{ form.hidden_tag() }}
                    {{ form.submit(class="btn rounded-0 bg-danger text-white font-monospace px-5") }}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock mainContent %}

HMS/templates/patient/genratePDF.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/css/bootstrap.min.css') }}">
</head>
<body>
</body>
    <script src="{{ url_for('static', filename='plugins/js/bootstrap.bundle.min.js') }}"></script>
    <script type="text/javascript">
        var data = {{data|tojson}}
        document.body.innerHTML = data.formData;
        window.onafterprint = function(event) {
            alert('Invoice generated. Patient Dischraged.');
            window.location.href = "/patientDischarge?next="+data.next+"&pid="+data.pid+"&dod="+data.dod+"&key="+data.key;
        };
        window.print();
    </script>
</html>

HMS/templates/patient/patientDetails.html
{% extends 'layout.html' %}
{% block mainContent %}
<div class="d-flex justify-content-center">
    <div class="card col-lg-4 col-md-8 col-12 mb-5 mt-3">
        <div class="card-header text-center bg-dark">
            <div class="card-title">
                <h2 class="font-monospace font-weight-bold text-info">Patient Details</h2>
            </div>
        </div>
        <div class="card-body alert-info">
            <div class="row">
                <p class="col-6 text-left font-weight-bold">SSN Id</p>
                <p class="col-6 text-right">{{ p.ssnid }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Patient Id</p>
                <p class="col-6 text-right">{{ p.patientId }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Patient Name</p>
                <p class="col-6 text-right">{{ p.name }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Patient Age</p>
                <p class="col-6 text-right">{{ p.age }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Date of Admission</p>
                <p class="col-6 text-right">{{ p.dateOfJoining }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Type of Bed</p>
                <p class="col-6 text-right">{{ p.roomType }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Address</p>
                <p class="col-6 text-right">{{ p.address }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">State</p>
                <p class="col-6 text-right">{{ p.state }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">City</p>
                <p class="col-6 text-right">{{ p.city }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Status</p>
                <p class="col-6 text-right">{% if p.status %}<span class="badge bg-primary">Available</span>{% else %}<span class="badge bg-secondary">Discharge</span>{% endif %}</p>
            </div>
        </div>
    </div>
</div>
{% endblock mainContent %}

HMS/templates/patient/update.html
{% extends 'layout.html' %}
{% from "includes/_form.html" import form_input_field_inline %}
{% from "includes/_form.html" import form_select_field_inline %}
{% block cssContent %}
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/css/select2-bootstrap4.min.css') }}">
{% endblock cssContent %}
{% block mainContent %}
<div class="d-flex justify-content-center mt-3">
    <div class="card col-lg-6 col-md-9 col-12 mb-5">
        <div class="card-header text-center font-monospace bg-dark">
            <h2 class="font-weight-bold text-info">Update Patient</h2>
        </div>
        <div class="card-body alert-info">
            <form method="POST" action="" novalidate>
                {{ form.hidden_tag() }}
                {{ form_input_field_inline(form.patientId) }}
                {{ form_input_field_inline(form.name) }}
                {{ form_input_field_inline(form.age) }}
                {{ form_input_field_inline(form.address) }}
                {{ form_select_field_inline(form.state) }}
                {{ form_select_field_inline(form.city) }}
                <div class="d-flex justify-content-center mt-5">
                    {{ form.submit(class="btn btn-outline-primary rounded-0 bg-dark
                    text-warning px-5") }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock mainContent %} 
{% block jsContent %}
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/city.js') }}"></script>
    <script>
        $('.select2').select2({
            theme: 'bootstrap4'
        });
    </script>
{% endblock jsContent %}