HMS/diagnostic/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, IntegerField, StringField, DecimalField, HiddenField
from wtforms.validators import DataRequired, ValidationError
from HMS.models import DiagnosticMaster


class NonValidatingSelectField(SelectField):
    def pre_validate(self, form):
        pass


class DiagnosticSubmitForm(FlaskForm):
    submitId = HiddenField('', validators=[DataRequired()])
    #submitQty = HiddenField('', validators=[DataRequired()])
    update = SubmitField('Update')

class AddTestForm(FlaskForm):
    testName = StringField('Test Name', validators=[DataRequired()])
    rate = DecimalField('Rate', validators=[DataRequired()])
    submit = SubmitField('Add Test')

    def validate_testName(self, testName):
        test = DiagnosticMaster.query.filter_by(testName=testName.data).first()
        if test:
            raise ValidationError('This Test already exists')

class TestDeleteForm(FlaskForm):
    id = HiddenField(validators=[DataRequired()])
    submit = SubmitField('Confirm Delete')


class TestUpdateForm(FlaskForm):
    testName = StringField('Test Name', validators=[DataRequired()], render_kw={'readonly': True})
    rate = DecimalField('Rate', validators=[DataRequired()])
    submit = SubmitField('Update Test')

HMS/diagnostic/__init__.py
from flask import Blueprint

diagnostic = Blueprint('diagnostic', __name__)

from HMS.diagnostic import routes

HMS/diagnostic/routes.py
from HMS import db
from HMS.diagnostic import diagnostic
from flask import render_template, redirect, request, url_for, flash, abort, jsonify
from flask_login import login_required
from HMS.diagnostic.forms import *
from HMS.models import DiagnosticMaster, Patient, Diagnostics
from HMS.patient.routes import checkPid


#Patient Details Routes
@diagnostic.route('/diagnostic', methods=['GET', 'POST'])
@login_required
def details():
    pid = request.args.get('pid')
    if pid is None:
        return redirect(url_for('main.search', next='diagnostic.details'))
    patient = checkPid(pid, True)
    title = 'Namaste Hospitals | Diagnostics'
    if request.method == 'POST':
        display = True
        id = request.form.get('submitId')
        id = list(id.split(","))  
        for i in range(len(id)):
            test = Diagnostics(patientId=pid, testId=id[i])
            db.session.add(test)
        db.session.commit()
        flash(f'New Tests issued to Patiend Id : {pid}', 'success')
        return redirect(url_for('diagnostic.details', pid=pid))
    issuetests = []
    form = DiagnosticSubmitForm()
    tests = DiagnosticMaster.query.all();
    issues = Diagnostics.query.filter_by(patientId=pid).all();
    for issue in issues:
        issueData = {}
        testDetail = DiagnosticMaster.query.filter_by(testId=issue.testId).first()
        issueData['name'] = testDetail.testName
        issueData['rate'] = testDetail.rate
        issuetests.append(issueData)
    return render_template('diagnostic/patienttests.html', title=title, form=form, pid=pid, tests=tests, patient=patient, issuetests=issuetests)



@diagnostic.route('/testDetails', methods=['POST'])
@login_required
def testDetails():
        test = DiagnosticMaster.query.get(int(request.form.get('testId')))
        if test:
            data = {
                "id": test.testId,
                "name": test.testName,
                "rate": test.rate
            }
            return jsonify(data)
        else:
            abort(404)


@diagnostic.route('/addtest', methods=['GET', 'POST'])
@login_required
def addtest():
    title = 'Namaste Hospitals | Add Test'
    form = AddTestForm()
    if request.method == 'POST' and form.validate_on_submit():
        test = DiagnosticMaster(testName=form.testName.data, rate=form.rate.data)
        db.session.add(test)
        db.session.commit()
        flash('New Test Successfully Added', 'success')
    return render_template('diagnostic/addtest.html', title=title, form=form)


@diagnostic.route('/allTestDetails', methods=['GET', 'POST'])
@login_required
def alltests():
    title = 'Namaste Hospitals | Diagnostics | Status'
    tests = DiagnosticMaster.query.all()
    return render_template('diagnostic/alltestdetails.html', tests=tests)


@diagnostic.route('/testDelete', methods=['GET', 'POST'])
@login_required
def testdelete():
    title = 'Namaste Hospitals | Diagnostics | Delete'
    t = request.args.get('test')
    form = TestDeleteForm()
    test = DiagnosticMaster.query.filter_by(testName=t).first()
    if request.method == 'POST':
        DiagnosticMaster.query.filter_by(testName=t).delete()
        db.session.commit()
        return redirect(url_for('diagnostic.alltests'))
    return render_template('diagnostic/deletetest.html', form=form, test=test)


@diagnostic.route('/testUpdate', methods=['GET', 'POST'])
@login_required
def testupdate():
    title = 'Namaste Hospitals | Diagnostics | Update'
    t = request.args.get('test')
    test = DiagnosticMaster.query.filter_by(testName=t).first()
    form = TestUpdateForm()
    form.testName.data = test.testName
    form.rate.data = test.rate
    if request.method == 'POST':
        rate = request.form.get('rate')
        if rate:
            test.rate = rate
        db.session.commit()
        flash(f'Diagnostic Update Successful', 'success')
        return redirect(url_for('diagnostic.alltests'))
    return render_template('diagnostic/updatetest.html', form=form)

HMS/templates/diagnostic/addtest.html
{% extends 'layout.html' %}
{% from 'includes/_form.html' import form_input_field_inline %}
{% block mainContent %}
<div class="d-flex justify-content-center my-5">
    <div class="card col-lg-6 col-md-9 col-12 px-3 py-4">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            {{ form_input_field_inline(form.testName) }}
            {{ form_input_field_inline(form.rate) }}
            <div class="d-flex justify-content-center">
                {{ form.submit(class="btn px-5 rounded-0 btn-info text-light text-uppercase font-monospace font-weight-bold") }}
            </div>
        </form>
    </div>
</div>
{% endblock mainContent %}

HMS/templates/diagnostic/alltestdetails.html
{% extends 'layout.html' %}  
{% block cssContent %}
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/css/dataTables.bootstrap4.min.css') }}">
{% endblock cssContent %}
{% block mainContent %}
<div class="card col-12 my-3">
    <div class="card-header text-center bg-dark">
        <div class="card-title">
            <h2 class="font-monospace font-weight-bold text-info">All Medicine's Details</h2>
        </div>
    </div>
    <div class="card-body alert-info">
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped" id="statustable">
                <thead class="bg-danger text-white">
                    <tr>
                        <th scope="col">Test Id</th>
                        <th scope="col">Test Name</th> 
                        <th scope="col">Rate</th>
                        <th scope="col">Update Test Details</th>
                        <th scope="col">Remove Test</th>
                    </tr>
                </thead>
                <tbody>
                    {% for t in tests %}   
                    <tr>
                        <td scope="row">{{ t.testId }}</td>
                        <td>{{ t.testName }}</td>
                        <td>{{ t.rate }}</td>
                        <td><a href="{{ url_for('diagnostic.testupdate', test=t.testName) }}" class="btn btn-primary text-white">Update</a></td>
                        <td><a href="{{ url_for('diagnostic.testdelete', test=t.testName) }}" class="btn btn-danger text-white">Delete</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock mainContent %}
{% block jsContent %}
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $("#statustable").DataTable({
            "info": true,
            "order": [0 ,'asc']
        });
    </script>
{% endblock jsContent %}

HMS/templates/diagnostic/deletetest.html
{% extends 'layout.html' %}
{% block mainContent %}
<div class="d-flex justify-content-center">
    <div class="card col-lg-4 col-md-8 col-12 mb-5 mt-3">
        <div class="card-header text-center bg-dark">
            <div class="card-title">
                <h2 class="font-monospace font-weight-bold text-info">Test Details</h2>
            </div>
        </div>
        <div class="card-body alert-info">
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Medicine Name</p>
                <p class="col-6 text-right">{{ test.testName }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Rate</p>
                <p class="col-6 text-right">{{ test.rate }}</p>
            </div>
            <div class="d-flex justify-content-center mt-5">
                <form action="" method="POST">
                    {{ form.hidden_tag() }}
                    {{ form.submit(class="btn rounded-0 bg-danger text-white font-monospace px-5") }}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock mainContent %}

HMS/templates/diagnostic/patienttests.html
{% extends 'layout.html' %}
{% from 'includes/_form.html' import form_select_field_inline %}
{% from 'includes/_form.html' import form_input_field_inline %}
{% block cssContent %}
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/css/select2-bootstrap4.min.css') }}">
{% endblock cssContent %}
{% block mainContent %}
<div class="row">
    <div class="card col-lg-4 col-md-8 col-12 px-0 border-dark">
        <div class="card-header bg-dark">
            <h3 class="text-center text-warning">Patient Details</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <p class="text-left col-5">Patient ID</p>
                <span class="text-right col-7">{{ patient.patientId }}</span>
            </div>
            <div class="row">
                <p class="text-left col-5">Name</p>
                <span class="text-right col-7">{{ patient.name }}</span>
            </div>
            <div class="row">
                <p class="text-left col-5">Age</p>
                <span class="text-right col-7">{{ patient.age }}</span>
            </div>
            <div class="row">
                <p class="text-left col-5">Address</p>
                <span class="text-right col-7">{{ patient.address+', '+patient.city+', '+patient.state }}</span>
            </div>
            <div class="row">
                <p class="text-left col-5">Date of Admission</p>
                <span class="text-right col-7">{{ patient.dateOfJoining }}</span>
            </div>
        </div>
    </div>
    <div class="col-lg-8 col-12">
        <table class="table table-striped table-bordered table-hover table-sm">
            <thead class="bg-dark text-warning text-center">
                <th class="col">Previous Tests Issued</th>
                <th class="col">Rate</th>
            </thead>
            <tbody class="text-center">
                {% for issuetest in issuetests %} 
                <tr>
                    <td scope="row">{{ issuetest.name }}</td>
                    <td>{{ issuetest.rate }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="d-flex justify-content-center my-5">
    <button onclick="testIssue()" class="btn btn-info border-0 px-5 text-decoration-none text-white font-weight-bold font-monospace text-uppercase">Issue Tests</button>
</div>
<div id="testIssue" class="mb-5" style="display: none;">
    <div class="d-flex justify-content-center">
        <div class="card col-lg-6 col-md-9 col-12 px-3 py-4">
            <form>
                <div class="row mb-3">
                    <label class="col-lg-3 col-form-label" for="testName">Test Name</label>
                    <div class="col-lg-9">
                        <select class="form-select select2" id="testName" name="testName" required>
                            {% for test in tests %}<option value="{{ test.testId }}">{{ test.testName }}</option>{% endfor %}
                        </select>
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    <input class="btn px-5 rounded-0 btn-info text-light text-uppercase font-monospace font-weight-bold" id="addTest" name="addTest" type="submit" value="Add Test">
                </div>
            </form>
        </div>
    </div>
</div>
<div class="mt-3 mb-5" id="formData" style="display: none;">
    <div class="d-flex justify-content-center">
        <div class="col-lg-6 col-md-9 col-12">
            <table class="table table-striped table-bordered table-hover table-sm">
                <thead class="bg-dark text-warning text-center">
                    <th class="col">Tests Issued Name</th>
                    <th class="col">Rate</th>
                </thead>
                <tbody id="returnData">
                </tbody>
            </table>
        </div>
    </div>
    <div class="d-flex justify-content-center mt-3">
        <div class="alert rounded-0 py-2 row bg-dark text-warning col-lg-6 col-md-9 col-12 font-weight-bold">
            <p class="col-6 py-0 my-0 text-right">Total Amount :</p>
            <span class="col-6 text-left" id="totalAmount"></span>
        </div>
    </div>
    <div class="d-flex justify-content-around">
        <a href="{{ url_for('diagnostic.details', pid=pid) }}" class="btn px-5 rounded-0 btn-secondary text-light text-uppercase font-monospace font-weight-bold">Reset</a>
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            {{ form.update(class="btn px-5 rounded-0 btn-success text-light text-uppercase font-monospace font-weight-bold") }}
        </form>
    </div>
</div>
{% endblock mainContent %}
{% block jsContent %}
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/diagnostic.js') }}"></script>
{% endblock jsContent %}

HMS/templates/diagnostic/updatetest.html
{% extends 'layout.html' %}
{% from 'includes/_form.html' import form_input_field_inline %}
{% block cssContent %}
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/css/dataTables.bootstrap4.min.css') }}">
{% endblock cssContent %}
{% block mainContent %}
<div class="d-flex justify-content-center my-5">
    <div class="card col-lg-6 col-md-9 col-12 px-3 py-4">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            {{ form_input_field_inline(form.testName) }}
            {{ form_input_field_inline(form.rate) }}
            <div class="d-flex justify-content-center">
                {{ form.submit(class="btn px-5 rounded-0 btn-info text-light text-uppercase font-monospace font-weight-bold") }}
            </div>
        </form>
    </div>
</div>
{% endblock mainContent %}

{% block jsContent %}
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/dataTables.bootstrap4.min.js') }}"></script>
   
    <script>
        $('.select2').select2({
            theme: 'bootstrap4'
        });
    </script>
{% endblock jsContent %}