HMS/pharmacist/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, IntegerField, StringField, DecimalField, HiddenField
from wtforms.validators import DataRequired, ValidationError
from HMS.models import MedicineMaster


class MedicineSubmitForm(FlaskForm):
    submitId = HiddenField('', validators=[DataRequired()])
    submitQty = HiddenField('', validators=[DataRequired()])
    update = SubmitField('Update')

class MedicineStoreForm(FlaskForm):
    medicineName = StringField('Medicine Name', validators=[DataRequired()])
    quantity = IntegerField('Quantity', validators=[DataRequired()])
    rate = DecimalField('Rate', validators=[DataRequired()])
    submit = SubmitField('Add Medicine')

    def validate_medicineName(self, medicineName):
        if MedicineMaster.query.filter_by(medicineName=medicineName.data).first():
            raise ValidationError('This Medicine is already exists')


class MedicineDeleteForm(FlaskForm):
    id = HiddenField(validators=[DataRequired()])
    submit = SubmitField('Confirm Delete')


class MedicineUpdateForm(FlaskForm):
    medicineName = StringField('Medicine Name', validators=[DataRequired()], render_kw={'readonly': True})
    quantity = IntegerField('Quantity', validators=[DataRequired()])
    rate = DecimalField('Rate', validators=[DataRequired()])
    submit = SubmitField('Update Medicine')

HMS/pharmacist/__init__.py
from flask import Blueprint

pharmacist = Blueprint('pharmacist', __name__)

from HMS.pharmacist import routes

HMS/pharmacist/routes.py
from HMS import db
from HMS.pharmacist import pharmacist
from flask import render_template, redirect, request, url_for, flash, abort, jsonify
from flask_login import login_required
from HMS.pharmacist.forms import MedicineStoreForm, MedicineSubmitForm, MedicineDeleteForm, MedicineUpdateForm
from HMS.models import MedicineMaster, Medicines, Patient
from HMS.patient.routes import checkPid


#Patient Details Routes
@pharmacist.route('/pharmacist', methods=['GET', 'POST'])
@login_required
def details():
    pid = request.args.get('pid')
    if pid is None:
        return redirect(url_for('main.search', next='pharmacist.details'))
    patient = checkPid(pid, True)
    title = 'Namaste Hospitals | Pharmacist'
    if request.method == 'POST':
        id = request.form.get('submitId')
        qty = request.form.get('submitQty')
        id =list(id.split(",")) 
        qty =list(qty.split(",")) 
        for i in range(len(id)):
            medDetail = MedicineMaster.query.filter_by(medicineId=id[i]).first()
            if int(medDetail.quantity) >= abs(int(qty[i])):
                medDetail.quantity = int(medDetail.quantity) - abs(int(qty[i]))
                medicine = Medicines(patientId=pid, medicineId=id[i], quantity=qty[i])
                db.session.add(medicine)
            else:
                pass
        db.session.commit()
        flash(f'New Medicines Issue to Patient ID : {pid}', 'success')
        return redirect(url_for('pharmacist.details', pid=pid))
    form = MedicineSubmitForm()
    medicines = MedicineMaster.query.all();
    issues = Medicines.query.filter_by(patientId=pid).all();
    issuemedicines = []
    for issue in issues:
        issueData = {}
        issueData['quantity'] = issue.quantity
        medDetail = MedicineMaster.query.filter_by(medicineId=issue.medicineId).first()
        issueData['name'] = medDetail.medicineName
        issueData['rate'] = medDetail.rate
        issuemedicines.append(issueData)
    return render_template('pharmacist/medicine.html', title=title, form=form, pid=pid, medicines=medicines, patient=patient, issuemedicines=issuemedicines)



@pharmacist.route('/medicineDetails', methods=['POST'])
@login_required
def medicineDetails():
        medicine = MedicineMaster.query.get(int(request.form.get('id')))
        if medicine:
            data = {
                "id": medicine.medicineId,
                "name": medicine.medicineName,
                "rate": medicine.rate
            }
            return jsonify(data)
        else:
            abort(404)

@pharmacist.route('/medicineQuantity', methods=['POST'])
@login_required
def medicineQuantity():
        medicine = MedicineMaster.query.get(int(request.form.get('id')))
        if medicine:
            return str(medicine.quantity)



@pharmacist.route('/medicineStore', methods=['GET', 'POST'])
@login_required
def medicine():
    title = 'Namaste Hospitals | Add Medicine'
    form = MedicineStoreForm()
    if request.method == 'POST' and form.validate_on_submit():
        medicine = MedicineMaster(medicineName=form.medicineName.data, quantity=form.quantity.data, rate=form.rate.data)
        db.session.add(medicine)
        db.session.commit()
        flash('New Medicine Successfully Added', 'success')
    return render_template('pharmacist/addmedicine.html', title=title, form=form)



@pharmacist.route('/allMedicineDetails', methods=['GET', 'POST'])
@login_required
def allmedicines():
    title = 'Namaste Hospitals | Medicines | Status'
    medicines = MedicineMaster.query.all()
    return render_template('pharmacist/allmedicinedetails.html', medicines=medicines)


@pharmacist.route('/medicineDelete', methods=['GET', 'POST'])
@login_required
def medicinedelete():
    title = 'Namaste Hospitals | Medicines | Delete'
    med = request.args.get('med')
    form = MedicineDeleteForm()
    medicine = MedicineMaster.query.filter_by(medicineName=med).first()
    if request.method == 'POST':
        MedicineMaster.query.filter_by(medicineName=med).delete()
        db.session.commit()
        flash(f'Medicine Removed from Store successfully', 'success')
        return redirect(url_for('pharmacist.allmedicines'))
    return render_template('pharmacist/deletemedicine.html', form=form, medicine=medicine)


@pharmacist.route('/medicineUpdate', methods=['GET', 'POST'])
@login_required
def medicineupdate():
    title = 'Namaste Hospitals | Medicines | Update'
    med = request.args.get('med')
    medicine = MedicineMaster.query.filter_by(medicineName=med).first()
    form = MedicineUpdateForm()
    form.medicineName.data = medicine.medicineName
    form.quantity.data = medicine.quantity
    form.rate.data = medicine.rate
    if request.method == 'POST':
        print(request.form)
        quantity = request.form.get('quantity')
        rate = request.form.get('rate')
        if quantity:
            medicine.quantity = quantity
        if rate:
            medicine.rate = rate
        db.session.commit()
        flash(f'Medicine Update Successful', 'success')
        return redirect(url_for('pharmacist.allmedicines'))
    return render_template('pharmacist/updatemedicine.html', form=form)

HMS/templates/pharmacist/addmedicine.html
{% extends 'layout.html' %}
{% from 'includes/_form.html' import form_input_field_inline %}
{% block mainContent %}
<div class="d-flex justify-content-center my-5">
    <div class="card col-lg-6 col-md-9 col-12 px-3 py-4">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            {{ form_input_field_inline(form.medicineName) }}
            {{ form_input_field_inline(form.quantity) }}
            {{ form_input_field_inline(form.rate) }}
            <div class="d-flex justify-content-center">
                {{ form.submit(class="btn px-5 rounded-0 btn-info text-light text-uppercase font-monospace font-weight-bold") }}
            </div>
        </form>
    </div>
</div>
{% endblock mainContent %}

HMS/templates/pharmacist/allmedicinedetails.html
{% extends 'layout.html' %}  
{% block cssContent %}
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/css/dataTables.bootstrap4.min.css') }}">
{% endblock cssContent %}
{% block mainContent %}
<div class="card col-12 my-3">
    <div class="card-header text-center bg-dark">
        <div class="card-title">
            <h2 class="font-monospace font-weight-bold text-info">All Medicine's Details</h2>
        </div>
    </div>
    <div class="card-body alert-info">
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped" id="statustable">
                <thead class="bg-danger text-white">
                    <tr>
                        <th scope="col">Medicine Id</th>
                        <th scope="col">Medicine Name</th> 
                        <th scope="col">Quantity</th>
                        <th scope="col">Rate</th>
                        <th scope="col">Update Medicine</th>
                        <th scope="col">Remove Meidicine</th>
                    </tr>
                </thead>
                <tbody>
                    {% for m in medicines %}   
                    <tr>
                        <td scope="row">{{ m.medicineId }}</td>
                        <td>{{ m.medicineName }}</td>
                        <td>{{ m.quantity }}</td>
                        <td>{{ m.rate }}</td>
                        <td><a href="{{ url_for('pharmacist.medicineupdate', med=m.medicineName) }}" class="btn btn-primary text-white">Update</a></td>
                        <td><a href="{{ url_for('pharmacist.medicinedelete', med=m.medicineName) }}" class="btn btn-danger text-white">Delete</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock mainContent %}
{% block jsContent %}
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $("#statustable").DataTable({
            "info": true,
            "order": [0 ,'asc']
        });
    </script>
{% endblock jsContent %}

HMS/templates/pharmacist/deletemedicine.html
{% extends 'layout.html' %}
{% block mainContent %}
<div class="d-flex justify-content-center">
    <div class="card col-lg-4 col-md-8 col-12 mb-5 mt-3">
        <div class="card-header text-center bg-dark">
            <div class="card-title">
                <h2 class="font-monospace font-weight-bold text-info">Medicine Details</h2>
            </div>
        </div>
        <div class="card-body alert-info">
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Medicine Name</p>
                <p class="col-6 text-right">{{ medicine.medicineName }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Qunatity</p>
                <p class="col-6 text-right">{{ medicine.quantity }}</p>
            </div>
            <div class="row">
                <p class="col-6 text-left font-weight-bold">Rate</p>
                <p class="col-6 text-right">{{ medicine.rate }}</p>
            </div>
            <div class="d-flex justify-content-center mt-5">
                <form action="" method="POST">
                    {{ form.hidden_tag() }}
                    {{ form.submit(class="btn rounded-0 bg-danger text-white font-monospace px-5") }}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock mainContent %}

HMS/templates/pharmacist/medicine.html
{% extends 'layout.html' %}
{% from 'includes/_form.html' import form_select_field_inline %}
{% from 'includes/_form.html' import form_input_field_inline %}
{% block cssContent %}
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/css/select2-bootstrap4.min.css') }}">
{% endblock cssContent %}
{% block mainContent %}
<div class="row">
    <div class="card col-lg-4 col-md-8 col-12 px-0 mb-3">
        <div class="card-header bg-dark">
            <h3 class="text-center text-warning">Patient Details</h3>
        </div>
        <div class="card-body">
            <div class="row mb-3">
                <p class="text-left col-5">Patient ID</p>
                <span class="text-right col-7">{{ patient.patientId }}</span>
            </div>
            <div class="row mb-3">
                <p class="text-left col-5">Name</p>
                <span class="text-right col-7">{{ patient.name }}</span>
            </div>
            <div class="row mb-3">
                <p class="text-left col-5">Age</p>
                <span class="text-right col-7">{{ patient.age }}</span>
            </div>
            <div class="row mb-3">
                <p class="text-left col-5">Address</p>
                <span class="text-right col-7">{{ patient.address+', '+patient.city+', '+patient.state }}</span>
            </div>
            <div class="row">
                <p class="text-left col-5">Date of Admission</p>
                <span class="text-right col-7">{{ patient.dateOfJoining }}</span>
            </div>
        </div>
    </div>
    <div class="col-lg-8 col-12">
        <table class="table table-striped table-bordered table-hover table-sm mb-3">
            <thead class="bg-dark text-warning text-center">
                <th class="col">Previous Medicines Issued</th>
                <th class="col">Quantity</th>
                <th class="col">Rate</th>
                <th class="col">Amount <small>( quantity * rate )</small></th>
            </thead>
            <tbody class="text-center">
                {% for issuemedicine in issuemedicines %} 
                <tr>
                    <td scope="row">{{ issuemedicine.name }}</td>
                    <td>{{ issuemedicine.quantity }}</td>
                    <td>{{ issuemedicine.rate }}</td>
                    <td>{{ issuemedicine.quantity*issuemedicine.rate }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="d-flex justify-content-center my-3">
    <button onclick="medicineIssue()" class="btn btn-info border-0 px-5 text-decoration-none text-white font-weight-bold font-monospace text-uppercase">Issue Medicines</button>
</div>
<div id="medicineIssue" class="mb-5" style="display: none;">
    <div class="d-flex justify-content-center">
        <div class="card col-lg-6 col-md-9 col-12 px-3 py-4">
            <form>
                <div class="row mb-3">
                    <label class="col-lg-3 col-form-label" for="medicineName">Medicine</label>
                    <div class="col-lg-9">
                        <select class="form-select select2" id="medicineName" name="medicineName" required>
                            <option value="0">Select Medicine Name</option>
                            {% for medicine in medicines %}<option value="{{ medicine.medicineId }}">{{ medicine.medicineName }}</option>{% endfor %}
                        </select>
                    </div>
                </div>        
                <div class="row mb-3">
                    <label class="col-lg-3 col-form-label" for="quantity">Quantity</label>
                    <div class="col-lg-9">
                        <select class="form-select select2" id="quantity" name="quantity" required>
                            <option value="0">Select Medicine Name First</option>
                        </select>
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    <button class="btn px-5 rounded-0 btn-info text-light text-uppercase font-monospace font-weight-bold" id="addMedicine" name="addMedicine"  disabled>Add Medicine</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="mt-3 mb-5" id="formData" style="display: none;">
    <div class="d-flex justify-content-center">
        <div class="col-lg-6 col-md-9 col-12">
            <table class="table table-striped table-bordered table-hover table-sm">
                <thead class="bg-dark text-warning text-center">
                    <th class="col">Medicines Issued Name</th>
                    <th class="col">Quantity</th>
                    <th class="col">Rate</th>
                    <th class="col">Amount <small>( quantity * rate )</small></th>
                </thead>
                <tbody id="returnData">
                </tbody>
            </table>
        </div>
    </div>
    <div class="d-flex justify-content-center mt-3">
        <div class="alert rounded-0 py-2 row bg-dark text-warning col-lg-6 col-md-9 col-12 font-weight-bold">
            <p class="col-6 py-0 my-0 text-right">Total Amount :</p>
            <span class="col-6 text-left" id="totalAmount"></span>
        </div>
    </div>
    <div class="d-flex justify-content-around">
        <a href="{{ url_for('pharmacist.details', pid=pid) }}" class="btn px-5 rounded-0 btn-secondary text-light text-uppercase font-monospace font-weight-bold">Reset</a>
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            {{ form.update(class="btn px-5 rounded-0 btn-success text-light text-uppercase font-monospace font-weight-bold") }}
        </form>
    </div>
</div>
{% endblock mainContent %}
{% block jsContent %}
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/medicine.js') }}"></script>
{% endblock jsContent %}

HMS/templates/pharmacist/updatemedicine.html
{% extends 'layout.html' %}
{% from 'includes/_form.html' import form_input_field_inline %}
{% block cssContent %}
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/css/dataTables.bootstrap4.min.css') }}">
{% endblock cssContent %}
{% block mainContent %}
<div class="d-flex justify-content-center my-5">
    <div class="card col-lg-6 col-md-9 col-12 px-3 py-4">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            {{ form_input_field_inline(form.medicineName) }}
            {{ form_input_field_inline(form.quantity) }}
            {{ form_input_field_inline(form.rate) }}
            <div class="d-flex justify-content-center">
                {{ form.submit(class="btn px-5 rounded-0 btn-info text-light text-uppercase font-monospace font-weight-bold") }}
            </div>
        </form>
    </div>
</div>
{% endblock mainContent %}

{% block jsContent %}
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='plugins/js/dataTables.bootstrap4.min.js') }}"></script>
   
    <script>
        $('.select2').select2({
            theme: 'bootstrap4'
        });
    </script>
{% endblock jsContent %}